import Head from 'next/head'
import { Navbar, Body, Footer } from '../components'

export default function Home() {

  

  return (
    <div className= " flex-col mt-1 justify-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
       
       <Navbar />
       <Body/>
       <Footer/>
  
      
    </div>
  )
}
